apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  generation: 4
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-wallet-chain-node
  name: wallet-chain-node
  namespace: default
  resourceVersion: '513750'
  uid: 04a29073-197f-41f5-8f68-0cfdafa1f022
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-wallet-chain-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-wallet-chain-node
      namespace: default
    spec:
      affinity: {}
      containers:
        - image: >-
            registry-intl-vpc.us-west-1.aliyuncs.com/fishcake-lab/wallet-chain-node:latest
          imagePullPolicy: Always
          name: wallet-chain-node
          ports:
            - containerPort: 8189
              name: rpc-port
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliyun-hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

