apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["dapplink-test/dapplink-xyz-portal"]'
    management.cattle.io/ui-managed: 'true'
  name: dapplink-xyz-portal
  namespace: dapplink-test
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-dapplink-test-dapplink-xyz-portal
  sessionAffinity: None
  type: ClusterIP