apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $index, $val := .Values.ports }}
    - port: {{ $val.portNumber }}
      targetPort: {{ $val.portNumber }}
      protocol: TCP
      name: {{  $val.name }}
    {{- end }}
    {{- with .Values.grpc }}
    port: {{ .Values.grpc.portNumber }}
      targetPort: {{ .Values.grpc.portNumber }}
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
