name: Acorus Image Build Only
on:
  pull_request:
    branches:
      - main
run-name: Build Image For Repo
  build:
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, Linux, X64, eks, mantle-default, "${{ github.event.inputs.env }}"]
    outputs:
      commit_sha: ${{ steps.get-commit-sha.outputs.commit_sha }}
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Get Commit Sha
        id: get-commit-sha
        run: |
          echo "::set-output name=commit_sha::$(git rev-parse --short=7 HEAD)"
      # - name: Login to Amazon ECR
      #   uses: aws-actions/amazon-ecr-login@v1
      #   id: login-ecr
      #   with:
      #     registries: 346612984731
      - name: Build Docker Image
        env:
          ECR_REGISTRY: "public.ecr.aws/d4s3o9q3"
          REPO: "acorus"
          #REF: ${{ github.event.inputs.ref }}
          COMMIT_SHA: ${{ steps.get-commit-sha.outputs.commit_sha }}
        run: |
          cmd="docker version"
          echo;  ">>> ${cmd}"; ${cmd}
          IMAGE_URL1=${ECR_REGISTRY}/${REPO}:${COMMIT_SHA}
          export NODE_OPTIONS="--max_old_space_size=9000"
          cmd="docker build --pull -f ../../Dockerfile -t ${IMAGE_URL1} ." 
          echo; ">>> ${cmd}"; ${cmd}
          docker tag ${IMAGE_URL1}
          cmd="docker push ${IMAGE_URL1}"
          echo; ">>> ${cmd}"; ${cmd}
          
